exports.DRAW = 'DRAW';
exports.FETCH_RING_INFO = 'FETCH_RING_INFO';
exports.RECEIVE_RING_INFO = 'RECEIVE_RING_INFO';
exports.JOIN_RING = 'JOIN_RING'
exports.LEAVE_RING = 'LEAVE_RING'
exports.DISCONNECT = 'DISCONNECT'